steps:
  # Build the frontend image from ./frontend
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/urbanestate-frontend:$COMMIT_SHA', './frontend']

  # Push to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/urbanestate-frontend:$COMMIT_SHA']

  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'run','deploy','urbanestate',
        '--image','${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/urbanestate-frontend:$COMMIT_SHA',
        '--region','${_REGION}',
        '--platform','managed',
        '--allow-unauthenticated',
        '--port','80'
      ]

substitutions:
  _REGION: europe-west2
  _REPO: urbanestate-images
