steps:
  # ==========================================================
  # Step 1: Inject Secrets (Replace Placeholders)
  # ==========================================================
  - name: 'ubuntu'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Injecting secrets into Identity Service..."
        # Using | as delimiter to prevent errors if API keys contain slashes /
        sed -i 's|YOUR_FIREBASE_API_KEY|${_FIREBASE_API_KEY}|g' frontend/src/app/service/identity/identity.ts
        sed -i 's|YOUR_FIREBASE_PROJECT_ID|${_FIREBASE_PROJECT_ID}|g' frontend/src/app/service/identity/identity.ts
        
        echo "Injecting secrets into Posts Service..."
        sed -i 's|YOUR_FIREBASE_API_KEY|${_FIREBASE_API_KEY}|g' frontend/src/app/service/posts/posts.ts
        sed -i 's|YOUR_FIREBASE_PROJECT_ID|${_FIREBASE_PROJECT_ID}|g' frontend/src/app/service/posts/posts.ts

        echo "Injecting secrets into App Component (Maps)..."
        sed -i 's|YOUR_GOOGLE_MAPS_API_KEY|${_MAPS_API_KEY}|g' frontend/src/app/app.component.ts

  # ==========================================================
  # Step 2: Build the Docker Image
  # ==========================================================
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'europe-west1-docker.pkg.dev/$PROJECT_ID/urbanestate-repo/frontend:latest',
      './frontend'
    ]

  # ==========================================================
  # Step 3: Push Image to Artifact Registry
  # ==========================================================
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-west1-docker.pkg.dev/$PROJECT_ID/urbanestate-repo/frontend:latest']

  # ==========================================================
  # Step 4: Deploy to Cloud Run
  # ==========================================================
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'urbanestate-frontend'
      - '--image'
      - 'europe-west1-docker.pkg.dev/$PROJECT_ID/urbanestate-repo/frontend:latest'
      - '--region'
      - 'europe-west1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '80'

# ==========================================================
# Config: Logging Options
# ==========================================================
options:
  logging: CLOUD_LOGGING_ONLY

# ==========================================================
# Config: Substitutions (Variables)
# ==========================================================
substitutions:
  _FIREBASE_API_KEY: "needs-to-be-set-in-trigger"
  _FIREBASE_PROJECT_ID: "needs-to-be-set-in-trigger"
  _MAPS_API_KEY: "needs-to-be-set-in-trigger"

images:
  - 'europe-west1-docker.pkg.dev/$PROJECT_ID/urbanestate-repo/frontend:latest'