steps:
  # ==========================================================
  # Step 1: Inject Secrets (Replace Placeholders)
  # ==========================================================
  # This securely replaces the placeholder text in your Angular files 
  # with the actual API keys stored in Cloud Build Substitutions.
  - name: 'ubuntu'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        sed -i 's/YOUR_FIREBASE_API_KEY/${_FIREBASE_API_KEY}/g' frontend/src/app/service/identity/identity.ts
        sed -i 's/YOUR_FIREBASE_PROJECT_ID/${_FIREBASE_PROJECT_ID}/g' frontend/src/app/service/identity/identity.ts
        sed -i 's/YOUR_GOOGLE_MAPS_API_KEY/${_MAPS_API_KEY}/g' frontend/src/app/app.component.ts
        
        # Verify replacement (optional debug, allows seeing if it worked in logs - be careful not to log full keys)
        echo "Secrets injected into source code."

  # ==========================================================
  # Step 2: Build the Docker Image
  # ==========================================================
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'europe-west1-docker.pkg.dev/$PROJECT_ID/urbanestate-repo/frontend:latest',
      './frontend'
    ]

  # ==========================================================
  # Step 3: Push Image to Artifact Registry
  # ==========================================================
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-west1-docker.pkg.dev/$PROJECT_ID/urbanestate-repo/frontend:latest']

  # ==========================================================
  # Step 4: Deploy to Cloud Run
  # ==========================================================
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'urbanestate-frontend'
      - '--image'
      - 'europe-west1-docker.pkg.dev/$PROJECT_ID/urbanestate-repo/frontend:latest'
      - '--region'
      - 'europe-west1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '80'

# ==========================================================
# Config: Substitutions (Variables)
# ==========================================================
substitutions:
  _FIREBASE_API_KEY: "needs-to-be-set-in-trigger"
  _FIREBASE_PROJECT_ID: "needs-to-be-set-in-trigger"
  _MAPS_API_KEY: "needs-to-be-set-in-trigger"

images:
  - 'europe-west1-docker.pkg.dev/$PROJECT_ID/urbanestate-repo/frontend:latest'