substitutions:
  _REGION: europe-west2
  _REPO: urbanestate-repo
  _ZONE: europe-west2-a
  _VM_NAME: urbanestate-vm

steps:
  # 1) Build image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/urbanestate-frontend:$COMMIT_SHA",
        "./frontend"
      ]

  # 2) Push image to Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/urbanestate-frontend:$COMMIT_SHA"
      ]

  # 3) Create VM once (if missing) running the container
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        set -e
        if ! gcloud compute instances describe "${_VM_NAME}" --zone "${_ZONE}" >/dev/null 2>&1; then
          gcloud compute instances create-with-container "${_VM_NAME}" \
            --zone "${_ZONE}" \
            --machine-type "e2-micro" \
            --tags "http-server,https-server" \
            --container-image "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/urbanestate-frontend:$COMMIT_SHA" \
            --container-restart-policy=always \
            --container-port=80
        fi

  # 4) Update the VM container to the new image every build
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "compute","instances","update-container","${_VM_NAME}",
        "--zone","${_ZONE}",
        "--container-image","${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/urbanestate-frontend:$COMMIT_SHA"
      ]

images:
  - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/urbanestate-frontend:$COMMIT_SHA"

options:
  logging: CLOUD_LOGGING_ONLY